sudo: required
services:
  - docker

before_install:
  - docker build -t shaikhwahid/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shaikhwahid/react-test npm test -- --coverage

 after_success:
  - docker build -t shaikhwahid/multi-client ./client
  - docket build -t shaikhwahid/multi-nginx ./nginx
  - docker build -t shaikhwahid/multi-server ./server
  - docker build -t shaikhwahid/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push shaikhwahid/multi-client
  - docker push shaikhwahid/multi-nginx
  - docker push shaikhwahid/multi-server
  - docker push shaikhwahid/multi-worker

